#!/bin/bash

if [[ $1 == "keygen" ]]; then
	openssl req -x509 -nodes -days 100000 -newkey rsa:2048 -keyout privatekey.pem -out publickey.pem
elif [[ $1 == "encrypt" ]]; then
	openssl smime -encrypt -aes256 -in $2 -binary -outform DEM -out encrypted_patient_data publickey.pem
elif [[ $1 == "decrypt" ]]; then
     openssl smime -decrypt -in $2 -binary -inform DEM -inkey privatekey.pem -out patient_data 
else
    echo "Usage: ./transfer {[keygen] | [encrypt|decrypt] [file]}"
fi


